"""checkups photos checkup interval

Revision ID: 4390496d1600
Revises: 1bd8999a3a2d
Create Date: 2026-10-01 22:37:00.759217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = '4390496d1600'
down_revision: Union[str, Sequence[str], None] = '1bd8999a3a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkups',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('recorded_on', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('chest_cm', sa.Float(), nullable=True),
    sa.Column('waist_cm', sa.Float(), nullable=True),
    sa.Column('hips_cm', sa.Float(), nullable=True),
    sa.Column('arm_cm', sa.Float(), nullable=True),
    sa.Column('thigh_cm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_checkups_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_checkups_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_checkups_recorded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkups')),
    sa.UniqueConstraint('member_id', 'recorded_on', name=op.f('uq_checkups_member_id'))
    )
    with op.batch_alter_table('checkups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkups_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkups_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkups_recorded_on'), ['recorded_on'], unique=False)

    op.create_table('checkup_photos',
    sa.Column('checkup_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkup_id'], ['checkups.id'], name=op.f('fk_checkup_photos_checkup_id_checkups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_checkup_photos_gym_id_gyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkup_photos')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_checkup_photos_storage_key'))
    )
    with op.batch_alter_table('checkup_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkup_photos_checkup_id'), ['checkup_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkup_photos_gym_id'), ['gym_id'], unique=False)

    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkup_interval_days', sa.Integer(), server_default='7', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_column('checkup_interval_days')

    with op.batch_alter_table('checkup_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkup_photos_gym_id'))
        batch_op.drop_index(batch_op.f('ix_checkup_photos_checkup_id'))

    op.drop_table('checkup_photos')
    with op.batch_alter_table('checkups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkups_recorded_on'))
        batch_op.drop_index(batch_op.f('ix_checkups_member_id'))
        batch_op.drop_index(batch_op.f('ix_checkups_gym_id'))

    op.drop_table('checkups')
    # ### end Alembic commands ###
