"""ai plans

Revision ID: 2863737b5570
Revises: 4390496d1600
Create Date: 2026-10-01 22:58:32.393339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.core.db


# revision identifiers, used by Alembic.
revision: str = '2863737b5570'
down_revision: Union[str, Sequence[str], None] = '4390496d1600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_plans',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'failed', 'draft', 'published', 'archived', name='planstatus', native_enum=False, length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', app.core.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ai_plans_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_ai_plans_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_ai_plans_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], name=op.f('fk_ai_plans_published_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_plans'))
    )
    with op.batch_alter_table('ai_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_plans_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_plans_member_id'), ['member_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_plans_member_id'))
        batch_op.drop_index(batch_op.f('ix_ai_plans_gym_id'))

    op.drop_table('ai_plans')
    # ### end Alembic commands ###
