"""plans members memberships

Revision ID: 8315cdd2ba7f
Revises: b372c0de81b0
Create Date: 2026-10-01 20:33:58.448111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8315cdd2ba7f'
down_revision: Union[str, Sequence[str], None] = 'b372c0de81b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_value', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.Enum('day', 'week', 'month', 'year', name='durationunit', native_enum=False, length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joining_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('services', sa.JSON(), nullable=False),
    sa.Column('max_freeze_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_plans_gym_id_gyms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_gym_id'), ['gym_id'], unique=False)

    op.create_table('members',
    sa.Column('branch_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender', native_enum=False, length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('goal', sa.Enum('weight_loss', 'muscle_gain', 'general_fitness', 'strength', 'endurance', 'flexibility', 'sports', 'rehab', name='goal', native_enum=False, length=20), nullable=True),
    sa.Column('diet_pref', sa.Enum('veg', 'non_veg', 'eggetarian', 'vegan', name='dietpref', native_enum=False, length=20), nullable=True),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'advanced', name='experiencelevel', native_enum=False, length=20), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('preview_token', sa.String(length=64), nullable=False),
    sa.Column('preview_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name=op.f('fk_members_branch_id_branches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_members_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], name=op.f('fk_members_trainer_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('gym_id', 'phone', name=op.f('uq_members_gym_id')),
    sa.UniqueConstraint('preview_token', name=op.f('uq_members_preview_token'))
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_name'), ['name'], unique=False)

    op.create_table('memberships',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('duration_value', sa.Integer(), nullable=False),
    sa.Column('duration_unit', sa.Enum('day', 'week', 'month', 'year', name='durationunit', native_enum=False, length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('joining_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_freeze_days', sa.Integer(), nullable=False),
    sa.Column('frozen_days', sa.Integer(), nullable=False),
    sa.Column('freeze_start', sa.Date(), nullable=True),
    sa.Column('freeze_end', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_memberships_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], name=op.f('fk_memberships_gym_id_gyms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_memberships_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_memberships_plan_id_plans'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships'))
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index('ix_memberships_gym_id_end_date', ['gym_id', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_plan_id'), ['plan_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_plan_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_member_id'))
        batch_op.drop_index('ix_memberships_gym_id_end_date')
        batch_op.drop_index(batch_op.f('ix_memberships_gym_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_name'))
        batch_op.drop_index(batch_op.f('ix_members_gym_id'))

    op.drop_table('members')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_gym_id'))

    op.drop_table('plans')
    # ### end Alembic commands ###
